/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline": "#727971",
        "surface-dim": "#d9dad9",
        "on-background": "#191c1c",
        "on-primary": "#ffffff",
        "on-surface-variant": "#424841",
        "surface-variant": "#e1e3e2",
        "inverse-primary": "#a9d0ad",
        "secondary-fixed": "#d3e8d5",
        "error-container": "#ffdad6",
        "primary": "#092d15",
        "outline-variant": "#c2c8bf",
        "on-secondary-fixed-variant": "#394b3d",
        "inverse-on-surface": "#f0f1f0",
        "on-secondary-container": "#56695a",
        "on-primary-container": "#8ab08e",
        "background": "#f9f9f8",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#c5edc8",
        "tertiary-container": "#cba72f",
        "secondary": "#506354",
        "on-surface": "#191c1c",
        "secondary-container": "#d3e8d5",
        "on-tertiary-fixed": "#241a00",
        "on-primary-fixed-variant": "#2c4e33",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#a9d0ad",
        "on-secondary-fixed": "#0e1f13",
        "error": "#ba1a1a",
        "on-tertiary-container": "#4e3d00",
        "surface-container": "#edeeed",
        "surface-bright": "#f9f9f8",
        "on-tertiary-fixed-variant": "#574500",
        "tertiary-fixed": "#ffe088",
        "tertiary": "#735c00",
        "surface-container-highest": "#e1e3e2",
        "surface-tint": "#436649",
        "surface-container-high": "#e7e8e7",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f3f4f3",
        "secondary-fixed-dim": "#b7ccb9",
        "tertiary-fixed-dim": "#e9c349",
        "on-primary-fixed": "#00210b",
        "primary-container": "#214329",
        "surface": "#f9f9f8",
        "inverse-surface": "#2e3131",
        "on-error": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "margin-mobile": "16px",
        "max-width": "1440px",
        "margin-desktop": "40px",
        "base": "8px",
        "stack-lg": "32px",
        "container-margin-desktop": "40px",
        "container-margin-mobile": "16px",
        "stack-sm": "8px",
        "unit": "8px",
        "stack-md": "16px"
      },
      fontFamily: {
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-xl-mobile": ["Hanken Grotesk", "sans-serif"],
        "headline-xl": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-xl-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
